project:
  type: website
  output-dir: _site
  preview:
    port: 4200
    browser: false

website:
  title: "APT"
  site-url: "https://neeldhara.github.io/APT"
  description: "APT (Algorithms: Practice and Theory) is a virtual fortnightly seminar series focusing on algorithms and complexity."
  navbar:
    background: primary
    search: true
    left:
      - text: "Stay Updated"
        href: seminars.qmd
    right:
      - icon: youtube
        href: https://www.youtube.com/@APTSeminars
        aria-label: YouTube
      - icon: twitter
        href: https://twitter.com/APTSeminars
        aria-label: Twitter
      - icon: mastodon
        href: https://mathstodon.xyz/@APTSeminars
        aria-label: Mastodon
      - icon: cloud
        href: https://bsky.app/profile/aptseminars.bsky.social
        aria-label: Bluesky
      - icon: rss
        href: seminars-rss.xml
        aria-label: RSS
  # Removed feed configuration

format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Crimson+Pro:ital,wght@0,400;0,600;1,400;1,600&family=Source+Sans+3:ital,wght@0,400;0,600;1,400;1,600&display=swap" rel="stylesheet">
    mainfont: "Source Sans 3"
    monofont: "Source Code Pro"
    toc: false
    page-layout: full
    title-block-banner: false

page-footer:
  right: "Built with [Quarto](https://quarto.org/)"
