[build]
  publish = "_site"
  command = """
    wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.549/quarto-1.4.549-linux-amd64.deb && \
    sudo dpkg -i quarto-1.4.549-linux-amd64.deb && \
    quarto render
  """

[build.environment]
  PYTHON_VERSION = "3.9"
  
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
